@HotelListing.Api_HostAddress = https://localhost:7211


###

GET {{HotelListing.Api_HostAddress}}/api/countries

###

POST {{HotelListing.Api_HostAddress}}/api/countries
Content-Type: application/json
{
  "name": "TestCountry",
  "shortNam": "TC"
}

###
###
@id=1
DELETE {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###
@id=1
GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###
@id=1
PUT {{HotelListing.Api_HostAddress}}/api/countries/{{id}}
Content-Type: application/json

{
  "countryId":1,
  "name": "Jamaica",
  "shortNam": "J"
}

###

GET {{HotelListing.Api_HostAddress}}/api/hotels

###

POST {{HotelListing.Api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "name": "Hotel B",
  "address": "Address B",
  "rating": 4,
  "countryId": 1d
}




###
@id=1
GET {{HotelListing.Api_HostAddress}}/api/countries/{{id}}

###
@id=4
GET {{HotelListing.Api_HostAddress}}/api/hotels/{{id}}
